source "https://rubygems.org"

ruby "3.1.2"
gem "sinatra", "~>2.1.0"
gem "sinatra-contrib"
gem "erubis"
gem "rack-test"
gem "minitest"
gem "redcarpet"
gem "bcrypt"
gem "sanitize"
gem "sysrandom"
gem "pg"
